<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Branch;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Get all branches
        $branches = Branch::all();

        // 2. Master List from your provided data
        $masterInventory = [
            ['name' => 'Allopurinol 100mg', 'price' => 3.00],
            ['name' => 'Allopurinol 300mg', 'price' => 5.00],
            ['name' => 'Ambroxol 30mg', 'price' => 3.50],
            ['name' => 'Amlodipine 5mg', 'price' => 3.00],
            ['name' => 'Amlodipine 10mg', 'price' => 5.00],
            ['name' => 'Amoxcillin 250mg', 'price' => 3.00],
            ['name' => 'Amoxicillin 500mg', 'price' => 5.00],
            ['name' => 'Acyclovir 400mg', 'price' => 17.00],
            ['name' => 'Atenolol 50mg', 'price' => 4.00],
            ['name' => 'Atenolol 100mg', 'price' => 5.50],
            ['name' => 'Atorvastatin 20mg', 'price' => 7.50],
            ['name' => 'Atorvastatin 40mg', 'price' => 10.00],
            ['name' => 'Atorvastatin 80mg', 'price' => 15.00],
            ['name' => 'Azithromycin 500mg', 'price' => 70.00],
            ['name' => 'Betahistine 8mg', 'price' => 10.00],
            ['name' => 'Betahistine 16mg', 'price' => 15.00],
            ['name' => 'Betahistine 24mg', 'price' => 35.00],
            ['name' => 'Bisacodyl 5mg', 'price' => 2.00],
            ['name' => 'Butamirate citrate', 'price' => 18.00],
            ['name' => 'Carvedilol 6.25mg', 'price' => 5.00],
            ['name' => 'Carvedilol 12.5mg', 'price' => 10.00],
            ['name' => 'Carvedilol 25mg', 'price' => 9.00],
            ['name' => 'Calcium Carbonate 500mg', 'price' => 3.00],
            ['name' => 'Captopril 25mg', 'price' => 3.50],
            ['name' => 'Carbocisteine 500mg', 'price' => 5.00],
            ['name' => 'Cepalexin 500mg', 'price' => 7.00],
            ['name' => 'Cefixime 200mg', 'price' => 23.00],
            ['name' => 'Cefixime 400mg', 'price' => 33.00],
            ['name' => 'Cefuroxime 500mg', 'price' => 30.00],
            ['name' => 'Cetirizine 10mg', 'price' => 3.00],
            ['name' => 'Cinnarizine 25mg', 'price' => 2.50],
            ['name' => 'Ciprofloxacin 500mg', 'price' => 7.50],
            ['name' => 'Clindamycin 300mg', 'price' => 11.00],
            ['name' => 'Clopidogrel 75mg', 'price' => 10.00],
            ['name' => 'Cloxacillin 500mg', 'price' => 10.00],
            ['name' => 'Co-amoxicalv 625mg', 'price' => 30.00],
            ['name' => 'Co-amoxiclav 1g', 'price' => 58.00],
            ['name' => 'Colchicine 500mcg', 'price' => 4.00],
            ['name' => 'Cotrimoxazole 960mg', 'price' => 8.00],
            ['name' => 'Cloramphenicol 500mg', 'price' => 2.00],
            ['name' => 'Clarithromycin 500mg', 'price' => 49.00],
            ['name' => 'Celecoxib 200mg', 'price' => 10.00],
            ['name' => 'Celecoxib 400mg', 'price' => 15.00],
            ['name' => 'Dexamethasone', 'price' => 2.50],
            ['name' => 'Diclofenac 50mg', 'price' => 2.00],
            ['name' => 'Dliclofenac 100mg', 'price' => 3.00],
            ['name' => 'Dicycloverine 10mg', 'price' => 2.00],
            ['name' => 'Digoxin 250mcg', 'price' => 5.00],
            ['name' => 'Diphenhydramine 50mg', 'price' => 5.00],
            ['name' => 'Domperidone 10mg', 'price' => 5.00],
            ['name' => 'Doxycycline 100mg', 'price' => 8.00],
            ['name' => 'Doxofylline 200mg', 'price' => 15.00],
            ['name' => 'Doxofylline 400mg', 'price' => 23.00],
            ['name' => 'Esomeprazole 40mg', 'price' => 155.00],
            ['name' => 'Eperisone 50mg', 'price' => 39.00],
            ['name' => 'Etoricoxib 120mg', 'price' => 30.00],
            ['name' => 'Erythromycin 500mg', 'price' => 10.00],
            ['name' => 'Febuxoxtat 40mg', 'price' => 17.00],
            ['name' => 'Fenofibrate 160mg', 'price' => 10.00],
            ['name' => 'Fenofibrate 200mg', 'price' => 15.00],
            ['name' => 'Furosemide 20mg', 'price' => 2.00],
            ['name' => 'Furosemide 40mg', 'price' => 4.00],
            ['name' => 'Fluconazole 150mg', 'price' => 45.00],
            ['name' => 'Gliclazide 30mg', 'price' => 5.00],
            ['name' => 'Gliclazide 60mg', 'price' => 9.00],
            ['name' => 'Gliclazide 80mg', 'price' => 5.00],
            ['name' => 'Hyoscine Butylbromide 10mg', 'price' => 12.00],
            ['name' => 'Irbesartan 150mg', 'price' => 12.00],
            ['name' => 'Irbesartan 300mg', 'price' => 17.00],
            ['name' => 'Ibuprofen 200mg', 'price' => 4.00],
            ['name' => 'Ibuprofen 400mg', 'price' => 5.00],
            ['name' => 'Isosorbide Mononitrate 30mg', 'price' => 12.00],
            ['name' => 'Lagundi', 'price' => 5.00],
            ['name' => 'Loperamide 2mg', 'price' => 2.50],
            ['name' => 'Losartan 50mg', 'price' => 4.00],
            ['name' => 'Losartan 100mg', 'price' => 7.00],
            ['name' => 'Losartan + Amlodipine 50/5mg', 'price' => 12.00],
            ['name' => 'Mefenamic Acid 500mg', 'price' => 4.00],
            ['name' => 'Mefenamic Acid 250mg', 'price' => 3.00],
            ['name' => 'Metoclopramide 10mg', 'price' => 3.00],
            ['name' => 'Metformin 500mg', 'price' => 2.00],
            ['name' => 'Methylprednisolone 16mg', 'price' => 22.00],
            ['name' => 'Montelukast 4mg', 'price' => 7.00],
            ['name' => 'Metoprolol 50mg', 'price' => 2.00],
            ['name' => 'Montelukast 5mg', 'price' => 9.00],
            ['name' => 'Montelukast 10mg', 'price' => 10.00],
            ['name' => 'Metronidazole 500mg', 'price' => 5.00],
            ['name' => 'Montelukast + Levocetirizine 10mg/5mg', 'price' => 26.00],
            ['name' => 'Methyldopa 250mg', 'price' => 13.00],
            ['name' => 'Naproxen sodium 550mg', 'price' => 8.50],
            ['name' => 'Nifedipine 5mg', 'price' => 4.00],
            ['name' => 'Nifedipine 10mg', 'price' => 7.00],
            ['name' => 'Omeprazole 20mg', 'price' => 7.00],
            ['name' => 'Omeprazole 40mg', 'price' => 10.00],
            ['name' => 'Paracetamol 500mg', 'price' => 2.00],
            ['name' => 'Paracetamol + Ibuprofen', 'price' => 7.00],
            ['name' => 'Paracetamo + Tramadol', 'price' => 8.00],
            ['name' => 'Piroxicam 20mg', 'price' => 5.00],
            ['name' => 'Prednisone 5mg', 'price' => 2.00],
            ['name' => 'Prednisone 10mg', 'price' => 3.00],
            ['name' => 'Prednisone 20mg', 'price' => 6.00],
            ['name' => 'Pregabalin 75mg', 'price' => 15.00],
            ['name' => 'Pantoprazole + Domperidone', 'price' => 15.00],
            ['name' => 'Potassium Citrate 1080mg', 'price' => 12.00],
            ['name' => 'Pioglitazone 15mg', 'price' => 7.00],
            ['name' => 'Propranolol 10mg', 'price' => 2.00],
            ['name' => 'Propranolol 40mg', 'price' => 3.00],
            ['name' => 'Ranitidine 150mg', 'price' => 7.00],
            ['name' => 'Ranitidine 300mg', 'price' => 9.00],
            ['name' => 'Rosuvastatin 10mg', 'price' => 10.00],
            ['name' => 'Rosuvastatin 20mg', 'price' => 12.00],
            ['name' => 'Salbutamol 2mg', 'price' => 2.00],
            ['name' => 'Salbutamol 4mg', 'price' => 2.50],
            ['name' => 'Sambong 500mg', 'price' => 8.00],
            ['name' => 'Salbutamol 1mg/ml nebule', 'price' => 18.00],
            ['name' => 'Simvastatin 20mg', 'price' => 4.00],
            ['name' => 'Tamsulosin 400mg', 'price' => 24.00],
            ['name' => 'Sildenafil 100mg', 'price' => 65.00],
            ['name' => 'Simvastatin 40mg', 'price' => 6.00],
            ['name' => 'Sitagliptin 100mg', 'price' => 26.50],
            ['name' => 'Symdex 25mg/2mg/325mg', 'price' => 4.00],
            ['name' => 'Tranexamic acid 500MG', 'price' => 12.00],
            ['name' => 'Telmisartan 40mg', 'price' => 12.00],
            ['name' => 'Telmisartan 80mg', 'price' => 15.00],
            ['name' => 'Trimetazidine 35mg', 'price' => 10.00],
            ['name' => 'Ascorbic acid 500', 'price' => 3.00],
            ['name' => 'Vitamins B-complex 300mg/100mg/100mccg', 'price' => 3.00],
            ['name' => 'Folic acid 5mg', 'price' => 5.00],
            ['name' => 'Multivitamins + Iron', 'price' => 5.00],
            ['name' => 'Iron + folic acid', 'price' => 4.00],
            ['name' => 'Keatoanlogue', 'price' => 24.00],
            ['name' => 'Arcoxia 60 mg', 'price' => 65.00],
            ['name' => 'Arcoxia 90 mg', 'price' => 78.00],
            ['name' => 'Arcoxia 120mg', 'price' => 98.50],
            ['name' => 'Oral rehydration salt', 'price' => 10.00],
            ['name' => 'Ascof 300mg', 'price' => 7.00],
            ['name' => 'Acetylcysteine 600mg', 'price' => 26.00],
            ['name' => 'Fluimucil 100mg', 'price' => 14.00],
            ['name' => 'Fluimucil 200mg', 'price' => 20.00],
            ['name' => 'Fluimucil 600mg', 'price' => 45.00],
            ['name' => 'Alaxan FR', 'price' => 10.00],
            ['name' => 'Buscopan', 'price' => 33.00],
            ['name' => 'Kremil-S', 'price' => 9.50],
            ['name' => 'Dolfenal 500mg', 'price' => 35.00],
            ['name' => 'Diatabs 2mg', 'price' => 9.00],
            ['name' => 'Advil', 'price' => 10.00],
            ['name' => 'Medicol Advance 200', 'price' => 7.50],
            ['name' => 'Aspirin 80mg', 'price' => 5.50],
            ['name' => 'Atenurix 40mg', 'price' => 23.00],
            ['name' => 'Concore 10mg', 'price' => 57.00],
            ['name' => 'Dapagliflozin', 'price' => 43.00],
            ['name' => 'Rexidol', 'price' => 8.00],
            ['name' => 'Saridon', 'price' => 8.00],
            ['name' => 'Bioflu', 'price' => 9.00],
            ['name' => 'Biogesic', 'price' => 6.00],
            ['name' => 'Kiddelets', 'price' => 4.00],
            ['name' => 'Neozep', 'price' => 9.00],
            ['name' => 'Decolgen ND', 'price' => 8.00],
            ['name' => 'Decolgen Forte', 'price' => 9.00],
            ['name' => 'Nasatapp Tab', 'price' => 9.00],
            ['name' => 'Nasathera', 'price' => 6.00],
            ['name' => 'Decolsin', 'price' => 16.00],
            ['name' => 'Kremil-S advance', 'price' => 22.50],
            ['name' => 'Medicol Advance 400', 'price' => 15.00],
            ['name' => 'Robitussin', 'price' => 14.00],
            ['name' => 'Tuseran Forte', 'price' => 12.50],
            ['name' => 'Solmux', 'price' => 12.50],
            ['name' => 'Solmux advace', 'price' => 17.00],
            ['name' => 'Ponstan 500mg', 'price' => 45.00],
            ['name' => 'Potassium Durules 750mg', 'price' => 35.00],
            ['name' => 'Neobloc 50mg', 'price' => 5.00],
            ['name' => 'Neobloc 100mg', 'price' => 7.50],
            ['name' => 'Trajenta 10mg', 'price' => 57.50],
            ['name' => 'Buscopan Venus', 'price' => 40.00],
            ['name' => 'Dulcolax 5mg', 'price' => 27.00],
            ['name' => 'Skelan 550mg', 'price' => 22.00],
            ['name' => 'Flanax 550mg', 'price' => 27.00],
            ['name' => 'Drenex 3mg', 'price' => 32.00],
            ['name' => 'Decilone forte', 'price' => 35.00],
            ['name' => 'Twynsta 40/10mg', 'price' => 30.00],
            ['name' => 'Twynsta 40/5mg', 'price' => 29.00],
            ['name' => 'Twynsta 80/10mg', 'price' => 35.00],
            ['name' => 'Twynsta 80/5mg', 'price' => 35.00],
            ['name' => 'Bonamine 25mg', 'price' => 15.00],
            ['name' => 'Verlix 10mg', 'price' => 37.00],
            ['name' => 'Bonamine 12.5mg', 'price' => 12.00],
            ['name' => 'Zykast', 'price' => 34.00],
            ['name' => 'Bacillus Claussi', 'price' => 39.00],
            ['name' => 'Stresstabs', 'price' => 12.50],
            ['name' => 'Revicon forte', 'price' => 7.50],
            ['name' => 'Enervon C', 'price' => 11.00],
            ['name' => 'Poten-CEE + ZINC', 'price' => 9.00],
            ['name' => 'Myra E', 'price' => 14.00],
            ['name' => 'Iberet 500mg', 'price' => 32.00],
            ['name' => 'Propan with iron', 'price' => 35.00],
            ['name' => 'Mwmo plus gold', 'price' => 20.00],
            ['name' => 'Duphaston 10mg', 'price' => 90.00],
            ['name' => 'Appebon with iron', 'price' => 26.50],
            ['name' => 'Hemarate fa', 'price' => 34.50],
            ['name' => 'Calciumade', 'price' => 12.00],
            ['name' => 'Pharmaton Essential', 'price' => 27.00],
            ['name' => 'Neurobion', 'price' => 26.00],
            ['name' => 'Dolo-Neurobion', 'price' => 30.00],
            ['name' => 'Neurogen-E', 'price' => 15.50],
            ['name' => 'Myra Ultimate', 'price' => 22.00],
            ['name' => 'Sangobion', 'price' => 30.00],
            ['name' => 'Immunpro', 'price' => 10.00],
            ['name' => 'Centrum Advance', 'price' => 12.00],
            ['name' => 'Centrum Silver Advance', 'price' => 15.00],
            ['name' => 'Amoxicillin 250mg/5ml 60ml', 'price' => 68.00],
            ['name' => 'Amoxicillin 125mg/5ml 60ml', 'price' => 55.00],
            ['name' => 'Amoxicillin Drops 10ml', 'price' => 49.00],
            ['name' => 'Ambroxol 15mg/5ml 60ml', 'price' => 60.00],
            ['name' => 'Ambroxol 30mg/5ml 60ml', 'price' => 60.00],
            ['name' => 'Ambroxol drops 10ml', 'price' => 40.00],
            ['name' => 'Azithromycin 200mg/5ml', 'price' => 182.00],
            ['name' => 'Aluminum Magnesium 200mg/5ml', 'price' => 60.00],
            ['name' => 'Carbocisteine drops 1ml', 'price' => 50.00],
            ['name' => 'Carbocisteine 125mg/5ml', 'price' => 55.00],
            ['name' => 'Cotrimoxazole 240mg/5ml', 'price' => 60.00],
            ['name' => 'Cetirizine drops', 'price' => 40.00],
            ['name' => 'Cetirizine 5mg/5ml', 'price' => 70.00],
            ['name' => 'Cefalexin 125/5ml', 'price' => 55.00],
            ['name' => 'Cefalexin 250mg/5ml', 'price' => 70.00],
            ['name' => 'Cefixime 100mg/5ml 60ml', 'price' => 207.00],
            ['name' => 'Cefuroxime 250mg/5ml', 'price' => 170.00],
            ['name' => 'Clarithromycin 125mg/5ml', 'price' => 270.00],
            ['name' => 'Chlorampenicol 125mg/5ml', 'price' => 65.00],
            ['name' => 'Cloxacillin 250mg/5ml', 'price' => 70.00],
            ['name' => 'Co-amoxiclav 457mg/5ml', 'price' => 285.00],
            ['name' => 'Butamirate citrate 705mg/5ml', 'price' => 110.00],
            ['name' => 'Erythromycin 200mg/5ml', 'price' => 95.00],
            ['name' => 'Mefenamic 50mg/5ml', 'price' => 68.00],
            ['name' => 'Metronidazole 125/5ml', 'price' => 55.00],
            ['name' => 'Metoclopramide 5mg/5ml', 'price' => 62.00],
            ['name' => 'Lactulose 3.33mg/5ml 60ml', 'price' => 150.00],
            ['name' => 'Lactulose 3.35mg/5ml 120ml', 'price' => 190.00],
            ['name' => 'Symdex-D Drops 15ml', 'price' => 70.00],
            ['name' => 'Symdex-D 60ml', 'price' => 75.00],
            ['name' => 'Salbutamol 2mg/5ml 60ml', 'price' => 60.00],
            ['name' => 'Salbutamol+Guaifenesin 50mg/1mg/5ml 60ml', 'price' => 60.00],
            ['name' => 'Guaifenesin 100mg/5ml 60ml', 'price' => 60.00],
            ['name' => 'Iron 30mg/5ml', 'price' => 45.00],
            ['name' => 'Lagundi Leaf 60ml', 'price' => 65.00],
            ['name' => 'Lagundi leaf 120ml', 'price' => 110.00],
            ['name' => 'Domperidone 1mg/5ml 60ml', 'price' => 125.00],
            ['name' => 'Dicycloverine 10mg/5ml 60ml', 'price' => 70.00],
            ['name' => 'Diphenhydramine 12.5mg/5ml 60ml', 'price' => 60.00],
            ['name' => 'Paracetamol drops 15ml', 'price' => 45.00],
            ['name' => 'Paracetamol 125mg/5ml 60ml', 'price' => 55.00],
            ['name' => 'Paracetamol 250mg/5ml 60ml', 'price' => 60.00],
            ['name' => 'Restime 40mg/ml 10ml', 'price' => 135.00],
            ['name' => 'Asmacaire 60ml', 'price' => 95.00],
            ['name' => 'Biogesic dops', 'price' => 85.00],
            ['name' => 'Biogesic 120mg/5ml', 'price' => 98.00],
            ['name' => 'Biogesic 250mg/5ml', 'price' => 155.00],
            ['name' => 'Broncaire 60ml', 'price' => 125.00],
            ['name' => 'Calpol drops', 'price' => 102.50],
            ['name' => 'Calpol 120mg/5ml', 'price' => 115.00],
            ['name' => 'Calpol 250mg/5ml', 'price' => 166.00],
            ['name' => 'Disudrin drops', 'price' => 135.00],
            ['name' => 'Disudrin 60ml', 'price' => 146.00],
            ['name' => 'Dolan 200mg/5ml 60ml', 'price' => 160.00],
            ['name' => 'Dolan 100mg/5ml', 'price' => 114.00],
            ['name' => 'Glychlor 60ml', 'price' => 120.00],
            ['name' => 'Nasatapp drops 15ml', 'price' => 130.00],
            ['name' => 'Nasatapp 60ml', 'price' => 128.00],
            ['name' => 'Neozep drops', 'price' => 117.00],
            ['name' => 'Neozep 60ml', 'price' => 117.00],
            ['name' => 'Meptin 5mcg/5ml 60ml', 'price' => 271.00],
            ['name' => 'Mebendazole 200mg/ml 50ml', 'price' => 480.00],
            ['name' => 'Robitussin DM 60ML', 'price' => 154.00],
            ['name' => 'Robitussin DM 120ml', 'price' => 241.00],
            ['name' => 'Salinase Nasal drops', 'price' => 93.00],
            ['name' => 'Salinase Nasal Spray', 'price' => 122.00],
            ['name' => 'Salbutamol inhaler 100mcg', 'price' => 200.00],
            ['name' => 'Tempra drops', 'price' => 90.00],
            ['name' => 'Tempra 250mg/5ml', 'price' => 160.00],
            ['name' => 'Nutrillin drops 15 ml', 'price' => 98.00],
            ['name' => 'Nutrillin drops 30ml', 'price' => 145.00],
            ['name' => 'Nutrilin 120ml', 'price' => 208.00],
            ['name' => 'Propan drops', 'price' => 105.00],
            ['name' => 'PropaN TLC 60ML', 'price' => 135.00],
            ['name' => 'Propan TLC 120ml', 'price' => 234.00],
            ['name' => 'Ferlin 120ML', 'price' => 375.00],
            ['name' => 'Ferlin Drops 15ml', 'price' => 165.00],
            ['name' => 'Appebon Kid 60ml', 'price' => 135.00],
            ['name' => 'Appebon kid 120ml', 'price' => 205.00],
            ['name' => 'Cherifer forte 120ml', 'price' => 265.00],
            ['name' => 'Ceelin 60ml', 'price' => 98.00],
            ['name' => 'Ceelin 120ml', 'price' => 143.00],
            ['name' => 'Ceelin PLUS drops 15', 'price' => 105.00],
            ['name' => 'Ceelin plus 60ml', 'price' => 112.00],
            ['name' => 'Ceelin PLUS 120ML', 'price' => 185.00],
            ['name' => 'Tiki-tiki Star 60ml', 'price' => 78.00],
            ['name' => 'Tiki-tiki Drops 15ml', 'price' => 68.00],
            ['name' => 'Zinc 20mg/5ml', 'price' => 130.00],
            ['name' => 'Zinc 10mg/ml drops', 'price' => 117.00],
            ['name' => '0.9% Sodium Chloride', 'price' => 120.00],
            ['name' => 'Acetylcysteine 200mg', 'price' => 20.00],
            ['name' => 'Althea Pill', 'price' => 470.00],
            ['name' => 'Trust Pills', 'price' => 58.00],
            ['name' => 'Daphne Pills', 'price' => 145.00],
            ['name' => 'Lady Pill', 'price' => 54.00],
            ['name' => 'Diane Pill', 'price' => 719.00],
            ['name' => 'Micropil pill', 'price' => 80.00],
            ['name' => 'Marvelon pills', 'price' => 330.00],
            ['name' => 'Trust Condom', 'price' => 35.00],
            ['name' => 'Efficascent regular 25ml', 'price' => 32.00],
            ['name' => 'Efficascent regular 50ml', 'price' => 56.00],
            ['name' => 'Efficascent (ES) 25ML', 'price' => 37.00],
            ['name' => 'Efficascent(ES) 50ml', 'price' => 69.00],
            ['name' => 'Efficascent extreme 25ml', 'price' => 43.00],
            ['name' => 'Efficascent extreme 50ml', 'price' => 81.00],
            ['name' => 'Salonpas', 'price' => 68.00],
            ['name' => 'Omega 15ml', 'price' => 26.00],
            ['name' => 'Omega 30ml', 'price' => 37.00],
            ['name' => 'Omega 120ml', 'price' => 136.00],
            ['name' => 'Bethadine 15ml', 'price' => 35.00],
            ['name' => 'Bethadine 30ml', 'price' => 58.00],
            ['name' => 'Bethadine 60ml', 'price' => 120.00],
            ['name' => 'Manzanilla 25ml', 'price' => 21.00],
            ['name' => 'Manzanilla 100ml', 'price' => 55.00],
            ['name' => 'Sebo De Macho 10mg', 'price' => 33.00],
            ['name' => 'Petroleum Jelly 25g', 'price' => 55.00],
            ['name' => 'Alcamporado 25ml', 'price' => 18.00],
            ['name' => 'Salicylic Acid 50ml', 'price' => 25.00],
            ['name' => 'Xylogel', 'price' => 180.00],
            ['name' => 'BL cream', 'price' => 45.00],
            ['name' => 'Katialis 5g', 'price' => 38.00],
            ['name' => 'Katialis 35g', 'price' => 45.00],
            ['name' => 'Whitfields ointment 15g', 'price' => 65.00],
            ['name' => 'Ketoconazole 20mg/g 15g', 'price' => 95.00],
            ['name' => 'Clotrimazole 1% cream 15g', 'price' => 110.00],
            ['name' => 'Silver Sulfadiazine 10mg/g cream 20g', 'price' => 180.00],
            ['name' => 'Clobetasol cream', 'price' => 95.00],
            ['name' => 'Mupirocin ointment', 'price' => 110.00],
            ['name' => 'EYE MO Blue', 'price' => 125.00],
            ['name' => 'Eye MO Green', 'price' => 115.00],
            ['name' => 'Eye MO Red', 'price' => 115.00],
            ['name' => 'Tobramycin ophthalmic solution 5ml', 'price' => 198.00],
            ['name' => 'Tobramycin + Dexamethasone 5ml', 'price' => 210.00],
            ['name' => 'Fungisol', 'price' => 170.00],
            ['name' => 'Isore 5ml', 'price' => 232.00],
            ['name' => 'Dequadin 250mcg', 'price' => 10.00],
            ['name' => 'Strepsils orange', 'price' => 76.00],
            ['name' => 'Strepsills blue', 'price' => 76.00],
            ['name' => 'Maden tawas', 'price' => 15.00],
            ['name' => 'RDL facial cleanser # 2 30ml', 'price' => 52.00],
            ['name' => 'RDL facial cleanser # 2 60', 'price' => 75.00],
            ['name' => 'RDL facial cleanser # 3 30ml', 'price' => 55.00],
            ['name' => 'RDL facial cleanser # 3 60ml', 'price' => 85.00],
            ['name' => 'MX3 coffee', 'price' => 23.00],
            ['name' => 'MX3 capsule', 'price' => 18.00],
            ['name' => 'Max Capsule', 'price' => 16.00],
            ['name' => 'Fish oil', 'price' => 8.00],
            ['name' => 'Liveraide', 'price' => 22.00],
            ['name' => 'Sleepwell', 'price' => 20.00],
            ['name' => 'Magnum C', 'price' => 12.00],
            ['name' => 'Magnum C coffee', 'price' => 17.00],
            ['name' => 'Off lotion 6ml', 'price' => 15.00],
            ['name' => 'Off lotion 50ml', 'price' => 130.00],
            ['name' => 'Biofitea', 'price' => 8.00],
            ['name' => 'Pregnancy test', 'price' => 50.00],
            ['name' => 'Acetone 25ml', 'price' => 25.00],
            ['name' => 'Acetone 60ml', 'price' => 33.00],
            ['name' => 'Gauze Pad', 'price' => 7.00],
            ['name' => 'Syringe 1cc', 'price' => 5.00],
            ['name' => 'Syringe 10cc', 'price' => 10.00],
            ['name' => 'Neb kit with mask Pedia Partners', 'price' => 95.00],
            ['name' => 'Neb kit with mask Adult Partners', 'price' => 95.00],
            ['name' => 'Soft tissue', 'price' => 15.00],
            ['name' => 'Cherub Baby Wipes 20 pcs', 'price' => 45.00],
            ['name' => 'Cherub Baby Wipes 80 pcs', 'price' => 110.00],
            ['name' => 'Lactacyd Baby bath 60ml', 'price' => 110.00],
            ['name' => 'Feeding Bottle 4oz', 'price' => 85.00],
            ['name' => 'Feeding bottle 9oz', 'price' => 95.00],
            ['name' => 'Ph Care 50ml', 'price' => 62.00],
            ['name' => 'Lactacyd Feminine wash 150ml', 'price' => 88.00],
            ['name' => 'Sisters night use 8 pads', 'price' => 38.00],
            ['name' => 'Bonna 0-6 months 1.2kg', 'price' => 845.00],
            ['name' => 'Bear brand junior 1.2kg', 'price' => 645.00],
            ['name' => 'Nestogen 1 0-6 months 340g', 'price' => 205.00],
            ['name' => 'Nestogen 1 0-6 months', 'price' => 89.00],
            ['name' => 'Lampein Large 15s', 'price' => 128.00],
            ['name' => 'Lampein Medium 15s', 'price' => 120.00],
            ['name' => 'Lampein Extra large 15s', 'price' => 135.00],
            ['name' => 'Lampein XXL 15s', 'price' => 145.00],
            ['name' => 'Super Twins Baby Pants Medium 26s', 'price' => 189.00],
            ['name' => 'Super Twins Baby Pants Large 26s', 'price' => 190.00],
            ['name' => 'Super Twins Baby Pants X-Large 26s', 'price' => 193.00],
            ['name' => 'Super Twins Baby Pants XX- Large 26s', 'price' => 198.00],
            ['name' => 'EQ Pants medium 10s', 'price' => 90.00],
            ['name' => 'EQ Pants Large 10s', 'price' => 100.00],
            ['name' => 'EQ Pants X- Large 10s', 'price' => 110.00],
            ['name' => 'Caress Adult Diaper medium 10s', 'price' => 190.00],
            ['name' => 'Caress Adult Diaper large 10s', 'price' => 245.00],
            ['name' => 'Caress Adult Diaper extra-large 10s', 'price' => 330.00],
            ['name' => 'Nature Spring 350ml', 'price' => 10.00],
            ['name' => 'Nature Spring 500ml', 'price' => 15.00],
            ['name' => 'Nature Spring 1 liter', 'price' => 25.00],
            ['name' => 'Nature Spring 1.5 liter', 'price' => 30.00],
            ['name' => 'Nature Spring Distilled Water 5L', 'price' => 68.00],
            ['name' => 'Nature Spring Distilled Water 10L', 'price' => 98.00],
            ['name' => 'Nature Spring Distilled Water 6L', 'price' => 85.00],
            ['name' => 'Non Rebreather Mask', 'price' => 430.00],
            ['name' => 'Robust tablet', 'price' => 175.00],
            ['name' => 'Robust capsule', 'price' => 295.00],
            ['name' => 'Tolak hangin', 'price' => 15.00],
            ['name' => 'Plaster', 'price' => 45.00],
            ['name' => 'Kool Fever', 'price' => 60.00],
            ['name' => 'White Flower 20ml', 'price' => 320.00],
            ['name' => 'Johnsons baby powder 50g', 'price' => 30.00],
            ['name' => 'Johnsons baby cologne 50ml', 'price' => 50.00],
            ['name' => 'Rdl facial cleanser 75 ml', 'price' => 35.00],
            ['name' => 'Eskinol 75ml', 'price' => 47.00],
            ['name' => 'Eskinol 150ml', 'price' => 75.00],
            ['name' => 'Casino alcohol 60ml', 'price' => 26.00],
            ['name' => 'Casino alcohol 150ml', 'price' => 39.00],
            ['name' => 'Casino alcohol 250ml', 'price' => 55.00],
            ['name' => 'Casino alcohol 500ml', 'price' => 90.00],
            ['name' => 'Toothache drops 7.5ml', 'price' => 95.00],
            ['name' => 'Bioderm Soap 60g', 'price' => 20.00],
            ['name' => 'Sulfur Soap 80g', 'price' => 46.00],
            ['name' => 'Grand Adult Diaper Large 18+2', 'price' => 375.00],
            ['name' => 'Grand Adult Diaper Medium 22+2', 'price' => 405.00],
            ['name' => 'Caress Adult Diaper large 2s', 'price' => 53.00],
            ['name' => 'Caress Adult Diaper medium 1s', 'price' => 26.00],
            ['name' => 'Grand Adult Diaper Large 2s', 'price' => 55.00],
            ['name' => 'Pau D arco 30ml', 'price' => 89.00],
            ['name' => 'Pau D arco 60ml', 'price' => 138.00],
            ['name' => 'Pau Masaje 60ml', 'price' => 85.00],
            ['name' => 'Nanz Liniment oil 30ml', 'price' => 65.00],
            ['name' => 'Nanz Liniment oil 30ml', 'price' => 110.00],
        ];

        // 3. Loop through EACH branch and add the inventory
        foreach ($branches as $branch) {
            foreach ($masterInventory as $item) {
                // Ensure unique barcode per item in each branch (simple random generation)
                // In production, you might want static barcodes if they share the same product
                $barcode = $branch->id . '-' . str_pad(rand(1, 99999), 6, '0', STR_PAD_LEFT);

                Product::create([
                    'branch_id' => $branch->id,
                    'barcode'   => $barcode,
                    'name'      => $item['name'],
                    'category'  => 'Fast Moving', // Default
                    'price'     => $item['price'],
                    'quantity'  => 200, // Forces 200 stock for ALL items
                    'low_stock_threshold' => 20,
                ]);
            }
        }
    }
}